services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: memorie
      POSTGRES_PASSWORD: memorie
      POSTGRES_DB: memorie
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
